version: '3'

services:
  api:
    container_name: wongames_api
    image: wongames/api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: wongames
      DATABASE_PASSWORD: wongames123
      DATABASE_NAME: wongames
      STRIPE_KEY: 'pk_test_51KKtieACWo4eufh4nkNyvJ3ssNJp0QgqElfMWUQXez2IFnjCzg0stHSaDixZlp6QgvyD6j9hu94y7SJqKgiTetYC00aw4Xf9Nh'
    ports:
      - '1337:1337'
    depends_on:
      - db
 
  db:
    container_name: wongames_db
    image: wongames/database:latest
    ports:
      - '5432:5432'